spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gather
    username: root
    password: 1234

  jpa:
    properties:
      hibernate:
        format_sql: true

    hibernate:
      ddl-auto: create
