spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gather
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  jwt:
    secret: ${JWT_SECRET}

  doc:
    api-docs:
      enabled: true
      path: /api-docs
    swagger-ui:
      enabled: true
      path: /swagger-ui.html
    paths-to-match:
      - /api/**

  security:
    oauth2:
      client:
        registration:
          google:
            client-name: ${GOOGLE_CLIENT_NAME}
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            authorization-grant-type: ${GOOGLE_AUTHORIZATION_GRANT_TYPE}
            scope: ${GOOGLE_SCOPE}
